### ISSUE TITLE
Variable $nombre del mensaje

### ISSUE THREAD

**Issue by lucianoar** [astornauta/skirience#1]
Hay un problema en la definición de la variable `$name` o `$nombre`
[Acá](https://github.com/astornauta/skirience/blob/51bcfeb2d27b5de0b6060613c0177c14d328e49a/mail/mail.php#L27) la variable está definida como:

```php
$name = $_POST["name"];
```

Pero al usarla [acá](https://github.com/astornauta/skirience/blob/51bcfeb2d27b5de0b6060613c0177c14d328e49a/mail/mail.php#L64) y [aca](https://github.com/astornauta/skirience/blob/51bcfeb2d27b5de0b6060613c0177c14d328e49a/mail/mail.php#L105) se la intenta llamar como:

```php
$message = "<b>Nombre:</b> " . $nombre;

//...

$headers .= "Reply-To: ".$nombre." <".$email.">". "\r\n";
```

**Comment by Tincho-gc** [comment]
# Solucionado, gracias!!
